### ISSUE TITLE
Crash spike on Crashlytics regarding -[PNDPairingController pairingStoreError:error:]

### ISSUE THREAD

**Issue by mshresthasentri** [pendo-io/pendo-mobile-sdk#132] opened 2024-04-04 16:37 UTC
Hi team, 

We are seeing a lot of crashes related to -[PNDPairingController pairingStoreError:error:] in our Crashlytics. Need help to figure out what seems to be the problem. 

We are just using [[PendoManager sharedManager] startSession: ] in our app and nothing else to start session.

**Comment by MaximShnirman** [comment] 2024-04-04 16:44
Can you add your crash log here please?

**Comment by mshresthasentri** [comment] 2024-04-04 16:54
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0xecb28 __exceptionPreprocess
1  libobjc.A.dylib                0x2af78 objc_exception_throw
2  CoreFoundation                 0x17deec +[NSObject(NSObject) _copyDescription]
3  CoreFoundation                 0x32300 ___forwarding___
4  CoreFoundation                 0x173760 _CF_forwarding_prep_0
5  Pendo                          0x11b7c8 -[PNDPairingController pairingStoreError:error:]
6  Pendo                          0xa983c __26-[PNDPairingStore setupWS]_block_invoke_2.155
7  libdispatch.dylib              0x213c _dispatch_call_block_and_release
8  libdispatch.dylib              0x3dd4 _dispatch_client_callout
9  libdispatch.dylib              0x125a4 _dispatch_main_queue_drain
10 libdispatch.dylib              0x121b8 _dispatch_main_queue_callback_4CF
11 CoreFoundation                 0x3751c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
12 CoreFoundation                 0x34218 __CFRunLoopRun
13 CoreFoundation                 0x33968 CFRunLoopRunSpecific
14 GraphicsServices               0x34e0 GSEventRunModal
15 UIKitCore                      0x22aedc -[UIApplication _run]
16 UIKitCore                      0x22a518 UIApplicationMain
17 sentrismart                    0x2479c main + 16 (main.m:16)
18 ???                            0x1c9752d84 (Missing)

**Comment by MikePendo** [comment] 2024-04-04 17:12
@mshresthasentri 
In order for us to help you  please edit/provide more data about the  issue according to our bug format 
**Platform + Version** , **SDK version**, **Framework** , **Steps to reproduce if possible**, **Full crash Log** i.e the whole threads. 
If you manage to reproduce you can attach logs

**Comment by MikePendo** [comment] 2024-04-04 18:30
I haven't looked at the code properly, BUT this part of the code is called during device pairing (kinda strange to see it in normal user flow). Can you please confirm you see those crashes from  your end users i.e not your PM or other person that tries to pair the device. 
How many effected users you have? 
Is you app on the appstore so we could try to download it and reproduce?
(We be able to look deeply into it on Sunday)

**Comment by mshresthasentri** [comment] 2024-04-04 19:04
That make sense because the only users who are affected by this are two of our internal team members who tag pages. But it is no fun when we are seeing 1000 crash reports on Crashlytics for them

**Comment by MikePendo** [comment] 2024-04-05 15:17
@mshresthasentri 
Which framework you are using? Native/flutter/RN 
Does the PM knows on which page it happens? 
Can you see on which page it happens in firebase (AFAIK there should be an option)
is you app available on App Store so we could try it to capture it on the same page
We had previously fixed some issues on pairing but non of them have a similar stack trace.
If you can share that additional info it could be nice so we will look at it more deeply on Sunday

**Comment by TehilaTaub** [comment] 2024-04-07 08:37
Hi, Do you have instaBug also?

**Comment by mshresthasentri** [comment] 2024-04-08 12:32
We do not have Instabug. And our app is called SentriKey Real Estate. 
https://apps.apple.com/us/app/sentrikey-real-estate/id643986446

**Comment by TehilaTaub** [comment] 2024-04-09 08:31
@mshresthasentri, we have opened an internal ticket for further investigation.

**Comment by orendayan** [comment] 2024-04-18 12:56
@mshresthasentri, we released v3.2 with some fixes in that area. Can you upgrade and see if it still happens?

**Comment by orendayan** [comment] 2024-05-01 11:29
I'm closing this issue since it hasn't responded two weeks

**Closed by orendayan** 2024-05-01 11:29 UTC
Labels: bug, iOS, Backlog
