### ISSUE TITLE
Crash on 3.0.1

### ISSUE THREAD

**Issue by dabaicaifen** [pendo-io/pendo-mobile-sdk#102] opened 2024-01-03 17:18 UTC
**Platform + Version**
IOS 17.2

**SDK Version**
Pendo 3.0.1

**Framework**
Native iOS

**Describe the bug**
Pendo crashes when tapping on some screen.

**To Reproduce**
1. Go to my app
2. Click on some feature
3. Crash

**Expected behavior**
No crash

**Logs**
Crash report:
[pendo_crash.txt](https://github.com/pendo-io/pendo-mobile-sdk/files/13821681/pendo_crash.txt)

**Comment by orendayan** [comment] 2024-01-04 11:15
Hi @dabaicaifen,
A few things that might help us to reproduce: 

- please open the debug log by following the below instructions and send it here:
https://github.com/pendo-io/pendo-mobile-sdk/blob/master/api-documentation/native-ios-apis.md#setdebugmode

- Is this issue reproduce for any screen you try navigating?
- Can you send us a snippet structure of the screen that doesn't open?
- And share your application name, if you can.

Thanks

**Comment by MikePendo** [comment] 2024-01-04 12:27
@dabaicaifen 
The crash is related to our new implementation of swiftui support. It's very hard to spot it without reproducing.
1. Any chance your app is on App Store and we can try it.
2. if you change your initialization with the following, as a work around : (will it still happen)
```
let options = PendoOptions()
 options.scanDepth = 15
 PendoManager.shared().setup(appKey, with: options)
```

**Comment by dabaicaifen** [comment] 2024-01-09 15:37
The following is the log right before the crash
```
[Pendo] [Tuesday, January 9, 2024 at 10:33 AM] ✅ 
[Pendo] [Tuesday, January 9, 2024 at 10:33 AM] ✅ -D- Sent analytics buffer successfully (id: 3) to server
[Pendo] [Tuesday, January 9, 2024 at 10:33 AM] ✅ -I- Finished background task '129'
[Pendo] [Tuesday, January 9, 2024 at 10:33 AM] ✅ -D- sent analytics buffer (id: 3) to server successfully.
[Pendo] [Tuesday, January 9, 2024 at 10:33 AM] ✅ Screen changed
[Pendo] [Tuesday, January 9, 2024 at 10:33 AM] ✅ Starting SwiftUI scan from topMostController: <_TtGC7SwiftUI19UIHostingControllerV8Dayforce12MessagesView_: 0x111902800>
[Pendo] [Tuesday, January 9, 2024 at 10:33 AM] ✅ A. elements found: 0 for view: nil
[Pendo] [Tuesday, January 9, 2024 at 10:33 AM] ✅ A. elements found: 0 for view: <UISplitViewController: 0x109e5a870>

**Comment by MikePendo** [comment] 2024-01-09 15:52
@dabaicaifen 
Any chance your app is on App Store and we can try it? We think we know where the issue might happen(as we have another customer that has the same issue) but we would like to verify it, as we cant reproduce it on our side

**Comment by MaximShnirman** [comment] 2024-01-10 07:50
added backlog to this one since i suspected there is another similar issue under work at the moment

**Comment by MaximShnirman** [comment] 2024-01-15 10:24
@dabaicaifen pls try fetching version 3.0.2 which should include a fix for this issue

**Comment by MaximShnirman** [comment] 2024-01-17 08:22
closing this for now, pls reopen in case this still happens

**Comment by dabaicaifen** [comment] 2024-01-22 20:52
hi @MaximShnirman , I tried 3.0.2 today, and it still crashes on my side. The debug message showed the same.

**Comment by MikePendo** [comment] 2024-01-23 02:40
@dabaicaifen
 its hard for us to say exactly what the exact reason for the crash.
1. is you app available on Appstore so we could try to reproduce the issue
OR
2. will it be possible for you to add us as test Flight user so we could try to reproduce the issue
OR
3. maybe u can create minimal sample code snippets so we could try to reproduce the issue

**Comment by MaximShnirman** [comment] 2024-01-23 08:15
@dabaicaifen can you please add the new crash log after updating to 3.02? (not the debug log)

**Comment by dabaicaifen** [comment] 2024-01-23 14:13
Hi @MaximShnirman , I'm happy to help, I asked my product to contact Pendo team.

**Comment by MikePendo** [comment] 2024-02-12 15:01
@dabaicaifen 
We got a response from you PM. And its seems you cant reproduce it any more. 
Is that the case? If yes can we close the issue 
If not we will need to have sample app to reproduce the issue as we didnt manage to reproduce it on our side with the same stack trace

**Comment by MikePendo** [comment] 2024-02-28 18:10
@dabaicaifen we reproduced the crash will be fixed in next HF release

**Comment by dabaicaifen** [comment] 2024-02-29 14:36
> @dabaicaifen we reproduced the crash will be fixed in next HF release

Thanks Mike, may I ask if Pendo can include the privacy manifest in this HF release?
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

**Comment by MikePendo** [comment] 2024-03-01 14:19
We will its in our road map but not in the HF (I think it will go to 3.2)

**Comment by dabaicaifen** [comment] 2024-03-01 14:24
> We will its in our road map but not in the HF (I think it will go to 3.2)

may I ask when the 3.2 is planned to release?

**Comment by MikePendo** [comment] 2024-03-01 14:30
I dont have an exact day right now. Let's do the following (you are not the first client who is asking for that).
Can you please open a separate issue for that?

**Comment by MikePendo** [comment] 2024-03-11 15:55
@dabaicaifen 
3.1.1 sdk was just release, please note we didnt managed reproduce the exact stack trace of you crash. 
We discovered a similar crash to yours that seems to be the root cause. 
If you have any sample project you want us to try or exact scenario on you app please share

**Closed by MikePendo** 2024-03-11 15:55 UTC
Labels: bug, iOS, Backlog
