### ISSUE TITLE
💥 Crash on `-[PNDRetroAnalyticsManager screenLeftAnalytics]`

### ISSUE THREAD

**Issue by msrutek-paylocity** [pendo-io/pendo-mobile-sdk#194] opened 2024-10-21 06:43 UTC
## **Platform + Version**
iPadOS 15.8.3, iPad Mini 4 

## **SDK Version**
3.4.0

## **Framework**
Native, SwiftUI

## **Describe the bug**
Crash of the app. Seeing `EXC_BAD_ACCESS`, this might related to incorrect memory management.

## **To Reproduce**
Yet unknown.

## **Expected behavior**
No crash.

## **Stack Trace**

```
Crashed: com.pendo.PNDWriteReadQueue
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000008c46b0b00 
0  libobjc.A.dylib                0x3120 objc_retain + 16
1  Pendo                          0x218e0 -[PNDRetroAnalyticsManager screenLeftAnalytics] + 28
2  Pendo                          0x1aff8 -[PNDPrivateAppDelegate sendAppSessionEnd:] + 64
3  Pendo                          0x1ba8c -[PNDPrivateAppDelegate enterForegroundNotification] + 660
4  Pendo                          0x1aae8 __57-[PNDPrivateAppDelegate observeAppLifeCycleNotifications]_block_invoke_2 + 28
5  libdispatch.dylib              0x63094 _dispatch_call_block_and_release + 24
6  libdispatch.dylib              0x64094 _dispatch_client_callout + 16
7  libdispatch.dylib              0xa73c _dispatch_lane_serial_drain$VARIANT$mp + 644
8  libdispatch.dylib              0xb1f4 _dispatch_lane_invoke$VARIANT$mp + 408
9  libdispatch.dylib              0x14ec8 _dispatch_workloop_worker_thread + 632
10 libsystem_pthread.dylib        0x1e00 _pthread_wqthread + 284
11 libsystem_pthread.dylib        0x192c start_wqthread + 8
```

**Comment by TehilaTaub** [comment] 2024-10-21 07:34
Hi @msrutek-paylocity 
It looks like this is coming from the same place, which is related to memory management.
We are working on a fix in our next HF, will update you when it's out.

**Comment by MikePendo** [comment] 2024-10-23 19:41
@msrutek-paylocity 
We just released new version 3.4.3, we had fixed significant memory issue that might arise on bad network. That might trigger or be the cause for the memory issue you have, any chance you could fetch the latest release and see and track the strange crashes once again. 
My comment applies to almost all issues you have found that related to memory, so I will copy paste that messages to the the relevant threads

**Comment by msrutek-paylocity** [comment] 2024-10-24 05:24
Hi @MikePendo , let us update and gather the results in the coming weeks/months!

**Comment by TehilaTaub** [comment] 2024-11-03 09:10
Hi @msrutek-paylocity,
Please upgrade to 3.4.3 and if you notice similar issues, please open a new ticket with the crash logs.
Closing this one now.

**Closed by TehilaTaub** 2024-11-03 09:10 UTC
Labels: iOS
